---
project : tmail
title   : TMail
brief   : Ruby Mail Handler
contact : Mikel Lindsaar <raasdnil AT gmail.com>
email   : tmail-talk@rubyforge.org
authors :
  - Minero Aoki
  - Mikel Lindsaar

description:
  TMail is a Ruby-based mail handler. It allows you
  to compose stadards compliant emails in a
  very Ruby-way.

loadpath:
  - lib
  - ext/tmailscanner

exclude: [pkg, doc]

